import { Link } from 'react-router-dom';
import { useState } from 'react';
import { money, useApp } from '../context/AppContext';
import Icon from '../components/Icon';
export default function AccountPage() {
  const { user, orders, wishlist, logout } = useApp();
  const [rating, setRating] = useState(0);
  const [feedback, setFeedback] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const [feedbackError, setFeedbackError] = useState('');
  const userOrders = orders.filter(o => o.userId === (user?.id || 'preview-customer'));
  return <div className="shell page-spacing"><p className="eyebrow">YOUR HIMA</p><div className="section-heading"><h1 className="page-title">Make yourself at home.</h1>{user ? <button className="underlined-button" onClick={logout}>Leave preview account</button> : <Link className="text-link" to="/login">Explore your profile <Icon name="arrow"/></Link>}</div>
    <div className="account-overview"><div><Icon name="user"/><h2>{user?.name || 'Hima Guest'}</h2><p>Preview profile · No personal details stored</p>{user?.role === 'admin' && <Link className="text-link" to="/admin">Store management</Link>}</div><Link to="/wishlist"><Icon name="heart"/><h2>{wishlist.length} saved {wishlist.length === 1 ? 'piece' : 'pieces'}</h2><p>All the things you’ve had your eye on. <Icon name="arrow" width="17" height="17"/></p></Link></div>
    <div className="section-heading"><h2 className="subheading">Your preview orders</h2><span className="muted">Available during this session</span></div>
    {userOrders.length ? <div className="order-list">{userOrders.map(o => <article className="order-card" key={o.id}><div className="order-card-heading"><div><h3>{o.id}</h3><p>{new Date(o.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p></div><span className="status-label">{o.status} · Preview</span></div><div className="order-items">{o.items.map(i => <div key={i.lineId}><img src={i.imageUrl} alt="" width="52" height="65"/><div><Link to={`/product/${i.id}`}>{i.name}</Link><p>{i.size} · Qty {i.quantity}</p></div><span>{money(i.price * i.quantity)}</span></div>)}</div><div className="order-card-total"><span>No payment taken</span><strong>Estimated total {money(o.total)}</strong></div></article>)}</div> : <div className="empty-orders"><Icon name="bag" width="30" height="30"/><h3>Your story starts here.</h3><p>When you complete a preview checkout, your sample order will appear here.</p><Link className="text-link" to="/shop">Find your first favorite <Icon name="arrow"/></Link></div>}
    <form className="feedback-form" onSubmit={e => { e.preventDefault(); if (!rating) { setFeedbackError('Choose a rating before saving your feedback.'); return; } try { sessionStorage.setItem('hima-feedback', JSON.stringify({ rating, feedback })); setSubmitted(true); setFeedbackError(''); } catch { setFeedbackError('Feedback could not be saved in this browser. Please try again.'); } }}><h2 className="subheading">How did it feel?</h2><p>Try the feedback form. Your response is saved only in this browser session.</p>{submitted ? <p className="feedback-success" role="status"><Icon name="check"/> Your preview feedback is saved. Thank you.</p> : <><fieldset className="rating-fieldset"><legend className="sr-only">Rate your shopping experience</legend>{[1,2,3,4,5].map(n => <label key={n} className={rating >= n ? 'rated' : ''}><input type="radio" name="rating" value={n} checked={rating === n} onChange={() => setRating(n)}/><span aria-hidden="true">★</span><span className="sr-only">{n} {n === 1 ? 'star' : 'stars'}</span></label>)}</fieldset><label htmlFor="feedback" className="sr-only">Your feedback</label><textarea id="feedback" value={feedback} onChange={e => setFeedback(e.target.value)} maxLength={500} placeholder="Anything you’d like to share? (Optional)" rows={3}/>{feedbackError && <p className="field-error" role="alert">{feedbackError}</p>}<button className="button button-dark" type="submit">Save preview feedback <Icon name="arrow"/></button></>}</form>
  </div>;
}

