import { Link, useSearchParams } from 'react-router-dom';
import Icon from '../components/Icon';
export default function HelpPage() {
  const [params] = useSearchParams();
  const topic = params.get('topic') || 'shopping';
  return <div className="help-page shell page-spacing"><p className="eyebrow">A LITTLE HELP, RIGHT HERE</p><h1 className="page-title">Good to know.</h1><p className="page-description">The details for a more considered shopping experience.</p><div className="help-layout"><nav aria-label="Help topics">{[['shopping','Shopping with Hima'],['shipping','Delivery & returns'],['sizing','Size guide'],['privacy','Your privacy']].map(([key,label]) => <Link key={key} to={`/help?topic=${key}`} className={key === topic ? 'selected' : ''} aria-current={key === topic ? 'page' : undefined}>{label}<Icon name="arrow" width="17" height="17"/></Link>)}</nav><div className="help-content" key={topic}>
      {topic === 'shipping' ? <><h2>Delivery & returns</h2><p>Hima is currently a storefront preview. You can explore the collection and try a sample checkout, but orders are not charged or dispatched.</p><h3>Delivery estimates in this preview</h3><p>The sample bag includes an $8 delivery estimate for orders below $100, and complimentary delivery at $100 or more. Tax is not calculated in the preview.</p><h3>When shopping goes live</h3><p>Delivery destinations, timeframes, taxes, and the return policy will be shown before a real purchase can be made.</p><Link to="/shop" className="text-link">Back to the collection <Icon name="arrow"/></Link></>
      : topic === 'sizing' ? <><h2>Find your fit.</h2><p>Use this illustrative guide to explore the size selection. Final garment measurements will accompany the live collection. Measurements below are approximate body measurements in inches.</p><div className="table-scroll" tabIndex={0} role="region" aria-label="Clothing size guide"><table><caption>Clothing · approximate inches</caption><thead><tr><th scope="col">Size</th><th scope="col">Chest / bust</th><th scope="col">Waist</th><th scope="col">Hip</th></tr></thead><tbody>{[['XS','32–33','24–25','34–35'],['S','34–35','26–27','36–37'],['M','36–37','28–29','38–39'],['L','38–40','30–32','40–42'],['XL','41–43','33–35','43–45']].map(row => <tr key={row[0]}>{row.map((cell,i) => i === 0 ? <th scope="row" key={i}>{cell}</th> : <td key={i}>{cell}</td>)}</tr>)}</tbody></table></div><h3>Denim</h3><p>Numbered denim sizes refer to the approximate waist measurement in inches. For example, size 28 is approximately a 28-inch waist.</p><h3>Shoes</h3><p>The preview uses US women’s shoe sizing: US 6 ≈ 9.1 inches, 7 ≈ 9.4, 8 ≈ 9.6, 9 ≈ 9.9, 10 ≈ 10.2, and 11 ≈ 10.5. These are approximate foot lengths, not verified measurements for the illustrated shoes.</p><h3>How to measure</h3><p>Use a soft measuring tape. Measure around the fullest part of your chest and hips, and the narrowest part of your waist. Keep the tape comfortably level.</p></>
      : topic === 'privacy' ? <><h2>Your privacy</h2><p>Your bag and saved pieces are stored in this browser so they can stay with you when you return. Clearing this site’s browser data removes them.</p><p>Preview profiles, inventory edits, and sample orders last for the current page session. Feedback is saved in this browser’s session storage. Delivery details are not saved or submitted to a server, and the preview never asks for card details.</p><p>Style suggestions use the collection already on this page. Your prompts are not sent to an AI service. Fonts are requested from Google Fonts; product images are served with the website.</p><p>This is the privacy explanation for the preview. A complete policy for live shopping will be available before launch.</p></>
      : <><h2>A little more you.</h2><p>Explore the collection, save your favorites with the heart button, and choose a size to add a piece to your bag.</p><details open><summary>Can I place a real order?<Icon name="plus" width="18" height="18"/></summary><p>This is a storefront preview with an illustrative catalog. Checkout creates a sample order only. No payment is taken and no products are shipped.</p></details><details><summary>Where are my saved pieces?<Icon name="plus" width="18" height="18"/></summary><p>Open the heart in the navigation, or <Link className="inline-link" to="/wishlist">view your saved pieces here</Link>. Favorites are kept in this browser.</p></details><details><summary>Do I need an account?<Icon name="plus" width="18" height="18"/></summary><p>You can browse and try checkout as a guest. The <Link className="inline-link" to="/login">account preview</Link> lets you explore a sample profile without sharing personal details.</p></details><details><summary>Can I get help putting a look together?<Icon name="plus" width="18" height="18"/></summary><p>Open the Style finder in the lower corner. Choose a mood or search for a piece to see suggestions from the collection.</p></details></>}
    </div></div></div>;
}

